// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"context"
	"github.com/google/wire"
	"go.uber.org/zap"
	"rest_demo/internal/handler"
	"rest_demo/internal/repository"
	"rest_demo/internal/server"
	"rest_demo/internal/service"
	"rest_demo/pkg/app"
	"rest_demo/pkg/cache"
	"rest_demo/pkg/db"
	"rest_demo/pkg/jwt"
	"rest_demo/pkg/llm"
	"rest_demo/pkg/payment/wechat"
	"rest_demo/pkg/redis"
	"rest_demo/pkg/server/http"
	"rest_demo/pkg/websocket"
)

// Injectors from wire.go:

func NewApp(contextContext context.Context, logger *zap.Logger, msConfig *db.MsConfig, config *http.Config, serviceConfig *service.Config, jwtConfig *jwt.Config, redisConfig *redis.Config, weChatPayConfig *wechat.WeChatPayConfig, cacheConfig *cache.Config, llmConfig *llm.Config) (*app.App, func(), error) {
	jwtJWT := jwt.NewJWT(jwtConfig)
	cacheCache, err := cache.NewCache(cacheConfig)
	if err != nil {
		return nil, nil, err
	}
	clientManager := websocket.NewWsManager(logger)
	serviceService := service.NewService(serviceConfig, logger, jwtJWT, cacheCache, clientManager)
	msDb, err := db.NewMsDB(msConfig)
	if err != nil {
		return nil, nil, err
	}
	repositoryRepository := repository.NewRepository(msDb)
	sysUserRepository := repository.NewSysUserRepository(repositoryRepository)
	loginService := service.NewLoginService(serviceService, sysUserRepository)
	jsapiClient := wechat.NewJSAPIClient(weChatPayConfig)
	loginHandler := handler.NewLoginHandler(loginService, jsapiClient)
	llmService := service.NewLLMService(llmConfig, logger)
	llmHandler := handler.NewLLMHandler(llmService, llmConfig, logger)
	client, err := redis.NewRedis(redisConfig)
	if err != nil {
		return nil, nil, err
	}
	httpServer := server.NewHTTPServer(logger, config, jwtJWT, loginHandler, llmHandler, client)
	appApp := newApp(httpServer)
	return appApp, func() {
	}, nil
}

// wire.go:

var repositorySet = wire.NewSet(db.NewMsDB, jwt.NewJWT, redis.NewRedis, cache.NewCache, wechat.NewJSAPIClient, websocket.NewWsManager, repository.NewRepository, repository.NewSysUserRepository)

var serviceSet = wire.NewSet(service.NewService, service.NewLoginService, service.NewLLMService)

var handlerSet = wire.NewSet(handler.NewLoginHandler, handler.NewLLMHandler)

var serverSet = wire.NewSet(server.NewHTTPServer)

// build App
func newApp(httpServer *http.Server) *app.App {
	return app.NewApp(app.WithServer(httpServer), app.WithName("hobyadm-server"))
}
